AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
    CommitHash:
        Type: String

Resources:
    RecordSet:
        Type: AWS::Route53::RecordSet
        Properties:
            Name: petesmith.io
            HostedZoneId: !ImportValue PeteSmithIOHostedZone
            Type: A
            AliasTarget:
                DNSName: !GetAtt CloudFrontDistribution.DomainName
                HostedZoneId: Z2FDTNDATAQYW2
    CloudFrontDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Enabled: true
                DefaultRootObject: index.html
                Origins:
                  - Id: Bucket
                    DomainName: !Join
                      - ""
                      - - !ImportValue
                            "Fn::Join":
                              - ""
                              - - "Terminal-Homepage-Bucket-"
                                - !Ref CommitHash
                        - ".s3.us-east-1.amazonaws.com"
                    S3OriginConfig: {}
                Aliases:
                  - !ImportValue PeteSmithIODomain
                ViewerCertificate:
                    AcmCertificateArn: !ImportValue PeteSmithIORootCertificate
                    SslSupportMethod: sni-only
                    MinimumProtocolVersion: TLSv1
                DefaultCacheBehavior:
                    TargetOriginId: Bucket
                    ViewerProtocolPolicy: redirect-to-https
                    ForwardedValues:
                        QueryString: true
                PriceClass: PriceClass_100

Outputs:
    CloudFrontDistribution:
        Value: !Ref CloudFrontDistribution
